"""add_soft_delete_to_cloud_providers

Revision ID: b2d7e551d226
Revises: 5a9c8e7f2b4d
Create Date: 2025-10-30 18:01:52.781032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d7e551d226'
down_revision: Union[str, Sequence[str], None] = '5a9c8e7f2b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_deleted column with default False for existing rows
    op.add_column('cloud_providers', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('cloud_providers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cloud_providers_is_deleted'), 'cloud_providers', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_providers_is_deleted'), table_name='cloud_providers')
    op.drop_column('cloud_providers', 'deleted_at')
    op.drop_column('cloud_providers', 'is_deleted')
    # ### end Alembic commands ###
