"""add_ai_text_fields_to_recommendations

Revision ID: b8136224cf9c
Revises: 4febd077bb0f
Create Date: 2025-11-04 23:40:52.842193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8136224cf9c'
down_revision: Union[str, Sequence[str], None] = '4febd077bb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add AI-generated text fields
    op.add_column('optimization_recommendations', sa.Column('ai_short_description', sa.Text(), nullable=True))
    op.add_column('optimization_recommendations', sa.Column('ai_detailed_description', sa.Text(), nullable=True))
    op.add_column('optimization_recommendations', sa.Column('ai_generated_at', sa.DateTime(), nullable=True))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_dedup_provider_specific'), table_name='optimization_recommendations')
    op.drop_index(op.f('idx_verification_tracking'), table_name='optimization_recommendations')
    op.create_index(op.f('ix_optimization_recommendations_last_verified_at'), 'optimization_recommendations', ['last_verified_at'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_target_provider'), 'optimization_recommendations', ['target_provider'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_target_sku'), 'optimization_recommendations', ['target_sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_recommendations_target_sku'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_target_provider'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_last_verified_at'), table_name='optimization_recommendations')
    op.create_index(op.f('idx_verification_tracking'), 'optimization_recommendations', ['last_verified_at', 'status'], unique=False)
    op.create_index(op.f('idx_dedup_provider_specific'), 'optimization_recommendations', ['source', 'resource_id', 'recommendation_type', 'target_provider', 'target_sku'], unique=False)
    # ### end Alembic commands ###
    
    # Remove AI-generated text fields
    op.drop_column('optimization_recommendations', 'ai_generated_at')
    op.drop_column('optimization_recommendations', 'ai_detailed_description')
    op.drop_column('optimization_recommendations', 'ai_short_description')
