"""add provider_resource_types table

Revision ID: ce3f3c4645c9
Revises: 2c4970b953a4
Create Date: 2025-10-22 01:11:12.144677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3f3c4645c9'
down_revision: Union[str, Sequence[str], None] = '2c4970b953a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_resource_types',
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('unified_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('raw_aliases', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_type', 'unified_type', name='uq_provider_unified_type')
    )
    op.create_index(op.f('ix_provider_resource_types_provider_type'), 'provider_resource_types', ['provider_type'], unique=False)
    op.create_index(op.f('ix_provider_resource_types_unified_type'), 'provider_resource_types', ['unified_type'], unique=False)
    # ### end Alembic commands ###

    # Seed baseline known types for current providers
    conn = op.get_bind()
    try:
        seeds = [
            ('beget', 'server', 'Сервер', 'server', True, '["vps","server"]'),
            ('beget', 'domain', 'Домен', 'domain', True, '["domain"]'),
            ('selectel', 'server', 'Виртуальная машина', 'server', True, '["cloud_vm","server","vm"]'),
            ('selectel', 'volume', 'Диск', 'disk', True, '["volume","disk"]'),
        ]
        for provider_type, unified_type, display_name, icon, enabled, raw_aliases in seeds:
            conn.execute(
                sa.text(
                    """
                    INSERT INTO provider_resource_types
                    (provider_type, unified_type, display_name, icon, enabled, raw_aliases, created_at, updated_at)
                    VALUES (:provider_type, :unified_type, :display_name, :icon, :enabled, :raw_aliases, NOW(), NOW())
                    ON DUPLICATE KEY UPDATE updated_at = NOW()
                    """
                ),
                {
                    'provider_type': provider_type,
                    'unified_type': unified_type,
                    'display_name': display_name,
                    'icon': icon,
                    'enabled': enabled,
                    'raw_aliases': raw_aliases,
                }
            )
    except Exception:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_resource_types_unified_type'), table_name='provider_resource_types')
    op.drop_index(op.f('ix_provider_resource_types_provider_type'), table_name='provider_resource_types')
    op.drop_table('provider_resource_types')
    # ### end Alembic commands ###
