"""Add complete sync models

Revision ID: d26614473f34
Revises: 1d8b3833a084
Create Date: 2025-10-16 12:01:34.372670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26614473f34'
down_revision: Union[str, Sequence[str], None] = '1d8b3833a084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complete_syncs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_started_at', sa.DateTime(), nullable=False),
    sa.Column('sync_completed_at', sa.DateTime(), nullable=True),
    sa.Column('sync_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_providers_synced', sa.Integer(), nullable=True),
    sa.Column('successful_providers', sa.Integer(), nullable=True),
    sa.Column('failed_providers', sa.Integer(), nullable=True),
    sa.Column('total_resources_found', sa.Integer(), nullable=True),
    sa.Column('total_monthly_cost', sa.Float(), nullable=True),
    sa.Column('total_daily_cost', sa.Float(), nullable=True),
    sa.Column('cost_by_provider', sa.Text(), nullable=True),
    sa.Column('resources_by_provider', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('sync_config', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complete_syncs_user_id'), 'complete_syncs', ['user_id'], unique=False)
    op.create_table('provider_sync_references',
    sa.Column('complete_sync_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('sync_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('sync_order', sa.Integer(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('resources_synced', sa.Integer(), nullable=True),
    sa.Column('provider_cost', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complete_sync_id'], ['complete_syncs.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['cloud_providers.id'], ),
    sa.ForeignKeyConstraint(['sync_snapshot_id'], ['sync_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_sync_references_complete_sync_id'), 'provider_sync_references', ['complete_sync_id'], unique=False)
    op.create_index(op.f('ix_provider_sync_references_provider_id'), 'provider_sync_references', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_sync_references_sync_snapshot_id'), 'provider_sync_references', ['sync_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_sync_references_sync_snapshot_id'), table_name='provider_sync_references')
    op.drop_index(op.f('ix_provider_sync_references_provider_id'), table_name='provider_sync_references')
    op.drop_index(op.f('ix_provider_sync_references_complete_sync_id'), table_name='provider_sync_references')
    op.drop_table('provider_sync_references')
    op.drop_index(op.f('ix_complete_syncs_user_id'), table_name='complete_syncs')
    op.drop_table('complete_syncs')
    # ### end Alembic commands ###
